[build]
  publish = "public"
  command = "gatsby build"
  NETLIFY_USE_YARN = "true"
[build.environment]
  NODE_VERSION = "18"
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  [plugins.inputs]
  output_path = "reports/lighthouse.html"   
[[headers]]
  for = "/*"
  [headers.values]
    cache-control = ''',
	  public,
	  max-age=2592000'''
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Robots-Tag = "index"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Access-Control-Allow-Origin = '''
      https://viadelweb.com,
      https://analytics.viadelweb.cloud, 
    '''      
    Access-Control-Allow-Methods = '''
      POST, 
      GET,
      PUT,  
      DELETE,
      HEAD
    '''
    Access-Control-Allow-Credentials = "true"
    Vary = "Accept-Encoding"
    Permissions-Policy = '''
      accelerometer=(self),
      ambient-light-sensor=(self),
      autoplay=(self),
      camera=(self),
      encrypted-media=(self),
      fullscreen=(self),
      geolocation=(self),
      gyroscope=(self),
      magnetometer=(self),
      microphone=(self),
      midi=(self),
      payment=(self),
      picture-in-picture=(self),
      speaker=(self),
      usb=(self),
      vibrate=(self),
      vr=(self)
    '''
    Content-Security-Policy = "connect-src 'self' blob: https://analytics.viadelweb.cloud https://analytics.viadelweb.cloud/matomo.js https://ocsp.digicert.com; form-action 'self' ; font-src 'self' ; frame-src 'self' https://analytics.viadelweb.cloud ; img-src 'self' b ; manifest-src 'self'; media-src 'self' blob: https://analytics.viadelweb.cloud ; object-src 'self'; script-src 'self' script-src-elem 'self' blob:  ; style-src 'self' prefetch-src 'self';  worker-src 'self';"
[[headers]]
  for = "/static/*"
  [headers.values]
    cache-control = '''
	  public,
	  max-age=31536000'''